### ISSUE TITLE
Feature: add zoom in Marey diagram

### ISSUE THREAD

**Issue by joined** [plannerstack/PTDS.js#23]
Something like this would be nice: https://bl.ocks.org/mbostock/db6b4335bf1662b413e7968910104f0f

**Comment by joined** [comment]
This is even better actually http://bl.ocks.org/jgbos/9752277 because it enables zooming on only one of the two axes

**Comment by joined** [comment]
I managed to overcome the obstacle that was blocking this to happen, will be working on it for a bit

**Comment by joined** [comment]
@skinkie I was thinking what if we have something like this for the zoom/scroll? https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172

Obviously vertically instead of horizontally. I think it will work well together with everything else, including the ability to display only the journeys currently in the view.
In the "side graph" we'll have the time in the main axis, allowing to browse the information of one day and in the other one we can have something like the number of active journeys in each moment.

**Comment by skinkie** [comment]
Mmm... wouldn't you think that 'second' graph is a waste of space?

**Comment by joined** [comment]
We could make it very narrow and it would take the space that is currently taken by the scrollbar.
There is also no real need to display any information on its "y" axis so we can make it even narrower and treat it as a sort of enhanced scrollbar

**Comment by joined** [comment]
Something like this https://bl.ocks.org/joined/raw/07a5ef5c620d8b9ac28c6b70b0222dcb/

**Comment by skinkie** [comment]
It is very smooth :)

**Comment by joined** [comment]
Fixed with #46
