### ISSUE TITLE
Bug: a user in the spiral simulation cannot set a timestamp

### ISSUE THREAD

**Issue by skinkie** [plannerstack/PTDS.js#39]
When entering a timestamp and pressing enter, the timestamp will continue at the previous position, but not from the entered time.

**Comment by joined** [comment]
Ah it was never supposed to have that feature, will see now how feasible it is with the widget library that I'm using (dat.GUI)

**Comment by skinkie** [comment]
It is not a bug, it is a lacking feature ;)
