### ISSUE TITLE
Bug: make sure the highest value in the realtime data is used for the end of the graph

### ISSUE THREAD

**Issue by skinkie** [plannerstack/PTDS.js#41]
![image](https://user-images.githubusercontent.com/502394/37206780-5b33cc84-239a-11e8-90b8-8e126d876ebd.png)

**Comment by skinkie** [comment]
It might be a small fix to just add +30min or +1h

**Comment by joined** [comment]
I noticed this one, the problem is that I'm looking only at the static data to compute min and max time.
I'll look into how long it takes to use the realtime data otherwise I'll just add an offset like you said
