### ISSUE TITLE
Bug: is the end point used for colouring?

### ISSUE THREAD

**Issue by skinkie** [plannerstack/PTDS.js#42]
![image](https://user-images.githubusercontent.com/502394/37207871-3f4fc1e4-239f-11e8-9019-3fcccb4df9b0.png)

I see here that negative times are still green, that is something that I really don't want to see.

**Comment by joined** [comment]
Looks like expected behaviour to me.

Reference: #36 

> Feedback from HTM:
> -15 is too early
> -15-120 is ontime
> 120+ is late

The way you had implemented it with your pull request, from -15 to 0 the vehicle was considered "late", which does not make sense.
I fixed it with commit b76c5292fd6f981c92c50be88d6adf7a7078ea62.

**Comment by skinkie** [comment]
Ok, then I was wrong.
