### ISSUE TITLE
Bug: After zooming the start offset time is not correct anymore

### ISSUE THREAD

**Issue by skinkie** [plannerstack/PTDS.js#43]
![image](https://user-images.githubusercontent.com/502394/37208816-0722f2b0-23a3-11e8-877a-78988e7233d0.png)

**Comment by joined** [comment]
Can you explain better?

**Comment by skinkie** [comment]
If you zoom-in then scroll up, you end up at for example 10am, not 6am anymore.

**Comment by joined** [comment]
That's exactly what I was trying to explain to you earlier, the problem with having two levels of zoom. There is no easy fix.

**Comment by joined** [comment]
Fixed with #46
