### ISSUE TITLE
Feature: implement overlay with different journeyspattern in Marey

### ISSUE THREAD

**Issue by skinkie** [plannerstack/PTDS.js#9]
Support for drawing multiple different parts of journey patterns, with a pivot (example: pattern 1 is C-D-E-F, pattern 2 is B-E-F, pivot is E, the second pattern can be drawn 'on top' of the first, still maintaining the real distances.

**Comment by skinkie** [comment]
As specific example in the current file: HTM:16:222, HTM:16:228, HTM:16:229 are the same pattern. So are HTM:16:230 and HTM:16:231. HTM:16:225 is a subset of HTM:16:230/231 and therefore could also rendered without any effort.

Lets start simple, and manually configure that 230, 231 and 225 should be rendered.

**Comment by joined** [comment]
Closed with #55
